import './components/wa-app-bar';
import './components/wa-button';
import './components/wa-card';
import './components/wa-grid';
import './components/wa-icon';
import './components/wa-page';
import './components/wa-pane';
import './components/wa-tabs';
import './components/wa-tab-item';