import './components/wa-accordion.ts';
import './components/wa-app-bar.ts';
import './components/wa-badge.ts';
import './components/wa-breadcrumbs.ts';
import './components/wa-breadcrumb-item.ts';
import './components/wa-button.ts';
import './components/wa-card.ts';
import './components/wa-checkbox.ts';
import './components/wa-divider.ts';
import './components/wa-drawer.ts';
import './components/wa-empty-state.ts';
import './components/wa-grid.ts';
import './components/wa-icon.ts';
import './components/wa-input.ts';
import './components/wa-menu-item.ts';
import './components/wa-modal.ts';
import './components/wa-nav-bar.ts';
import './components/wa-notifications.ts';
import './components/wa-notification-item.ts';
import './components/wa-page.ts';
import './components/wa-pane.ts';
import './components/wa-popover.ts';
import './components/wa-progress-bar.ts';
import './components/wa-radio-button.ts';
import './components/wa-spinner.ts';
// import './components/wa-stepper.ts';
// import './components/wa-stepper-item.ts';
// import './components/wa-switch.ts';
// import './components/wa-switch-item.ts';
import './components/wa-tab-item.ts';
// import './components/wa-table.ts';
// import './components/wa-table-row.ts';
// import './components/wa-table-cell.ts';
import './components/wa-tabs.ts';
import './components/wa-tag.ts';
import './components/wa-text.ts';
import './components/wa-toggle.ts';
import './components/wa-tool.ts';
// import './components/wa-tooltip.ts';
import './components/wa-avatar.ts';
import './components/shared-styles.ts';